# Generated by Django 4.2.15 on 2024-08-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='product_name',
        ),
        migrations.AddField(
            model_name='image',
            name='product_name',
            field=models.CharField(default='older_prods', max_length=255),
        ),
    ]
